### ISSUE TITLE
Feature Enhancement - Support for Sengled multicolor bulbs

### ISSUE THREAD

**Issue by informationinsecurity** [jfarmer08/ha-sengledapi#17]
Your integration works great to turn on and off the Sengled bulbs! The only issue I have is that they do not seem to support any of the color changing features. If you are willing to work on this, I can provide you with any logs or details you might need.

**Comment by jfarmer08** [comment]
You are correct currently this will not support any color options for Sengled Bulbs. Do you have wifi bulbs or zigbee bulbs that requires the hub. I plan on adding support for this, but I currently do not have the multi color bulbs that goes with the hub. For the Wifi Color bulbs I have added some support and still adding.

**Comment by jfarmer08** [comment]
Any logs you have please feel free to share.

**Comment by informationinsecurity** [comment]
Thanks for the reply- I have the zigbee bulbs that require the hub. I am happy to provide logs - can you tell me which ones would be interesting to you?

**Comment by jfarmer08** [comment]
@informationinsecurity 
1. Setup your logger to print debug messages for this component by adding this to your `configuration.yaml`:
    ```yaml
    logger:
      default: warning
      logs:
        custom_components.sengledapi: debug
    ```
2. Restart HA
3. Verify you're still having the issue
4. File an issue in this Github Repository

**Comment by jfarmer08** [comment]
I have added some support for RGB if you want to pull down the https://github.com/jfarmer08/ha-sengledapi/tree/Dev
