### ISSUE TITLE
[Bug] Abnormally high level of DNS queries

### ISSUE THREAD

**Issue by thespad** [jfarmer08/ha-sengledapi#38]
ha-sengledapi appears to be sending DNS queries for element.cloud.sengled.com 4 times every 30 seconds; this equates to nearly 20,000 requests per day. Looks like 2 A and 2 AAAA lookups. I can't find an easy way to correlate the lookups to the internal logs but as I have two bulbs it would be reasonable to assume it's performing a pair of lookups for each.

I'm unsure if this is an issue with the plugin or something inherent to Home Assistant (Docker container) that can't be worked around.

**Comment by jfarmer08** [comment]
How many bulbs do you have?

**Comment by TheSpad** [comment]
Just the two.

**Comment by jfarmer08** [comment]
So it seems that HA is calling my Update every 30 seconds, ( I could change this, but i think it should be fine), but i am not sure why it would call it twice for the same controller. In the Sengled log you should see Sengled Bulb "name of Bulb" Updating every time it makes a call to element.cloud.sengled.

**Comment by SerahTheLioness** [comment]
Check the TTL of that DNS record: It could be set insanely low. Or the DNS caching isn't there.

**Comment by TheSpad** [comment]
FWIW I never managed to identify the underlying cause but I put in a horrible workaround that runs as a cron job
```bash
#! /bin/bash

cp /etc/hosts /tmp/hosts.new && sed -i '/element.cloud.sengled.com/d' /tmp/hosts.new && /usr/bin/nslookup eu.element.cloud.sengled.com | grep "Address" | tail -2 | awk '{print $NF}' | while read line; do echo $(echo "$line eu.element.cloud.sengled.com") >> /tmp/hosts.new; done

/usr/bin/nslookup element.cloud.sengled.com | grep "Address" | tail -2 | awk '{print $NF}' | while read line; do echo $(echo "$line element.cloud.sengled.com") >> /tmp/hosts.new; done && cat /tmp/hosts.new > /etc/hosts
```
Which injects the current IPs for element.cloud.sengled.com and eu.element.cloud.sengled.com into the HA docker container's hosts file so it doesn't need to perform external lookups.
