### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by mmatus1112** [jfarmer08/ha-sengledapi#41]
I have a HA via virtual machine and all works perfectly (still waiting for my BLUE to arrive). I was able to add the sengledapi into the HA and the lights show up with no issue. The problem comes when you want to turn the lights on or off: if the light is on and you turn it off, the light will turn off but the state in HA will go back to on after one second. You need to change the state 4 or 5 times for it to stay where it has to stay to show the correct state (on when on, off when off). The main issue with this is that scenes won't work if the correct state of lights is not ok.

**Comment by jfarmer08** [comment]
I will look into this issue.

**Comment by jfarmer08** [comment]
I am kind of seeing the same thing, but it's more of a delay. When I toggle the bulb off HA will toggle off but back on and the bulb itself will go off the first time. So the bulb is working with the toggle, but HA has a delay on the state change. I will see what I can go to fix this. 

I am preparing to move so I am not sure how soon I can do this, but will make my best efforts.

**Comment by mmatus1112** [comment]
Yes, the lights work ok with on and off. The HA toggle is the one that has issues. Take your time and good luck with your moving!!!!

Regards!

**Comment by Sandman224** [comment]
I have the exact same issue. I think the issue is that the code only requests the state of the device once after you send a change state command, while it should continue to request the state multiple times after a state change is sent until it sees the state change.

**Comment by mmatus1112** [comment]
any idea on how to resolve this issue? besides getting rid of the sengled lights  LOL

**Comment by jfarmer08** [comment]
Maybe someone can create a pull request with a fix to help? @mmatus1112 @Sandman224

**Comment by jfarmer08** [comment]
Corrected in version 1.2.3
