### ISSUE TITLE
No longer working with Sengled Hub?

### ISSUE THREAD

**Issue by thewoose** [jfarmer08/ha-sengledapi#42]
Hi,
I first installed the sengledapi integration a few months ago.  When I first installed it, it controlled all my lights, about 7 on a hub and one wifi light.  However, now the box rarely even shows up in the Integrations screen and it only will control my one wifi light.  The rest of them on the hub don't work.  The system sees their names, but is unable to control them.

**Comment by jfarmer08** [comment]
I am in the process of moving and so i cannot work on this for a few more weeks. If you have any logs that could help.

**Comment by ziuton** [comment]
I have the same problem i can see all my lights but i can't control them

**Comment by jfarmer08** [comment]
@ziuton Do you have any logs that would help?
