### ISSUE TITLE
[Bug] Setup failed for sengledapi: Integration not found

### ISSUE THREAD

**Issue by geek-baba** [jfarmer08/ha-sengledapi#45]
**Describe the bug**
Setup failed for sengledapi: Integration not found

**To Reproduce**
Once you update to 2021.05.4, the integration stopped working.

**System configuration**
System: Bare Metal
HA Version: OS 5.13
SengledApi Version: 0.2

**home-assistant.log**
Logger: homeassistant.setup
Source: setup.py:172
First occurred: 7:15:46 PM (1 occurrences)
Last logged: 7:15:46 PM

Setup failed for sengledapi: Integration not found.

**Comment by foreverinPanama** [comment]
Having the same issue after updating to today's release of home assistant. Looking through my logs it seems like the version number of this integration simply needs to conform to some standard being enforced my HA now. See below.


Version | core-2021.6.0



https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#versions

Log:
2021-06-02 22:13:06 ERROR (SyncWorker_4) [homeassistant.loader] The custom integration 'sengledapi' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by pjmbarlick** [comment]
Same issue here after updating to 2021.6.0 :(

**Comment by kailashrao** [comment]
Same issue, I checked the "Check Home Assistant Configuration" add on before and it said 
`Failed config
  General Errors: 
    - Component error: sengledapi - Integration 'sengledapi' not found.`
   I'm running 2021.5.5 right now (didn't update), I think @foreverinPanama already mentioned it, but I also believe it is the version key that is preventing the integration from working.

**Comment by foreverinPanama** [comment]
So I fixed mine locally, I don't know the first thing about how to properly use git so I can't make a branch or upload a commit or anything, but you need to edit the manifest.json file located under the config\custom_components\sengledapi\ folder

In there add a line with "version": "0.2", (I just matched the version displayed by the actual developers lol).

After that, restart home assistant, re-add; un-comment out the configuration.yaml lines for your login information, restart again and it should be up and running.

Good luck everyone.

{
  "domain": "sengledapi",
  "name": "Sengled Integration",
  "documentation": "https://github.com/jfarmer08/ha-sengledapi",
  "dependencies": [],
  "version": "0.2",
  "codeowners": ["@jfarmer08"],
  "requirements": ["paho-mqtt==1.5.0"],
  "icons": [
    "https://camo.githubusercontent.com/4e40f86270556ef2922b12694496746b7d96d6fd/68747470733a2f2f7a69676265652e626c616b61646465722e636f6d2f6173736574732f696d616765732f646576696365732f53656e676c65645f4531312d4731332e6a7067"
  ],
  "config_flow": false
}

**Comment by kailashrao** [comment]
> After that, restart home assistant, re-add; un-comment out the configuration.yaml lines for your login information, restart again and it should be up and running.

I added the version info in the manifest.json file and ran the "Check Home Assistant Config" add-on, I didn't get any errors and got the green light to update. But in your (@foreverinPanama) reply I'm not to sure what you mean by "re-add; un-comment out the configuration.yaml lines for your login information" Could you just clarify that part?

Thanks

**Comment by geek-baba** [comment]
> > After that, restart home assistant, re-add; un-comment out the configuration.yaml lines for your login information, restart again and it should be up and running.
> 
> I added the version info in the manifest.json file and ran the "Check Home Assistant Config" add-on, I didn't get any errors and got the green light to update. But in your (@foreverinPanama) reply I'm not to sure what you mean by "re-add; un-comment out the configuration.yaml lines for your login information" Could you just clarify that part?
> 
> Thanks

He must have disabled the integration by commenting the login info in configuration.yaml while troubleshooting and thats what he is referring to...

**Comment by geek-baba** [comment]
@jfarmer08 - could you update the master repo to fix this issue?

**Comment by jfarmer08** [comment]
@geek-baba @kailashrao @pjmbarlick I have made an the update based on this thread. Please let me know if this corrects the item.

**Comment by geek-baba** [comment]
> @geek-baba @kailashrao @pjmbarlick I have made an the update based on this thread. Please let me know if this corrects the item.

Thanks, the 0.2.1 fixed the error. However I have a question about the implementation of this integration:

1. Why this integration does not show up in the main integration page like other custom integration...
2. Why only entities show up and not devices like other custom integration...

**Comment by kailashrao** [comment]
It works! 🥳

**Comment by jfarmer08** [comment]
@geek-baba Ok so to answer your questions. I have not updated this integration for awhile and so to support the 2 items it would be a little more work on my part or someone else that can create a pull request. HA has come a long way since I first created this and so i am sure the whole project needs updated. Currently I just dont have the time.

**Comment by foreverinPanama** [comment]
Thanks for the official update @jfarmer08
