### ISSUE TITLE
Support for W31-N15 Confirmed

### ISSUE THREAD

**Issue by SerahTheLioness** [jfarmer08/ha-sengledapi#47]
Hey, Looks like the W31-N15 is supported fully with this. I have full control of the RGB color, temperature, brightness, and toggle. I don't quite know how to update the wiki myself but it's all working on my end as of 9/14/21

**Comment by jfarmer08** [comment]
Thank you.

**Comment by Stratoco** [comment]
![sengled](https://user-images.githubusercontent.com/91235979/147862670-2e93edb7-083d-4b25-8e17-e08821286e1a.jpg)

This is it, I have the same bulbs.

**Comment by Stratoco** [comment]
I would like to confirm that it does indeed work, I just connected four of them. Seems faster than the sengled app, too.

**Comment by shannonfritz** [comment]
How do you re-flash them?  I found an unopened box of four of them and would like to get Tasmota on there.  I was hoping to use Tuya Convert, but [the Blakadder site](https://templates.blakadder.com/sengled_W31-N15.html) indicates a USB-to-Serial, so I assume I need to get the bulb open somehow and find the right pin pads.  Any advice?
