### ISSUE TITLE
[Question] Possible kelvin conversion issue?

### ISSUE THREAD

**Issue by definitelyokay** [jfarmer08/ha-sengledapi#50]
Here, kelvin is being translated back into a percent value for the Sengled API, I believe:

https://github.com/jfarmer08/ha-sengledapi/blob/aa7cca514dba1ea170f1b95ed23902fc7886ecec/custom_components/sengledapi/sengledapi/devices/bulbs/bulb.py#L150-L154

Was the `200` actually supposed to be `2000`, as shown here?

https://github.com/jfarmer08/ha-sengledapi/blob/aa7cca514dba1ea170f1b95ed23902fc7886ecec/custom_components/sengledapi/sengledapi/devices/bulbs/bulb.py#L291-L296

I am not a HomeAssistant user, but I am writing a similar plugin for Homebridge. This plugin's code has been tremendously helpful, so I thought I might point this out and see if it was an oversight or by design (in which case I should implement the same).

**Comment by geezfools** [comment]
I seem to be having some color temp issues...

**Comment by jfarmer08** [comment]
@definitelyokay It has been a while since i looked at this code. To my knowledge I think this is correct, since sengled changes there value around also. I have since moved away from using Home Assistant and started using Homekit. Might be able to help with the cut over.
