### ISSUE TITLE
Feature Request: Effects

### ISSUE THREAD

**Issue by jnpetersen** [jfarmer08/ha-sengledapi#51]
In the app there is an option to select different types of effects.  Since the app doesn't allow you to group bulbs with an effect (I want them to be in sync) I thought there might be a way to trigger the effect through home assistant and just create a scene that it would ultimately do what I want.

If this is possible, that would be fantastic.

**Comment by zaw9c1** [comment]
YES!!  Please.  !!!

**Comment by HamzaETTH** [comment]
If someone want to give it a try, the mqtt publish message payload for the effect are the following.
![image](https://user-images.githubusercontent.com/73552421/188323717-e5f5272c-db56-4b92-85c0-c65d204b1a91.png)
