### ISSUE TITLE
Official Integration? 

### ISSUE THREAD

**Issue by ssc327** [jfarmer08/ha-sengledapi#54]
Hi, any reason this requires the setup of another integration repository?

**Comment by zaw9c1** [comment]
Its very popular LED bulbs in the market no No controller out there natively support it.

**Comment by ssc327** [comment]
Sorry, maybe my question was unclear. Some integrations for HA are installable through the Ui simply by selecting them from a list. This one is not like that and requires extra setup, why is that?

**Comment by Stratoco** [comment]
> Sorry, maybe my question was unclear. Some integrations for HA are installable through the Ui simply by selecting them from a list. This one is not like that and requires extra setup, why is that?

There's an "official" list of integrations. This one is just not on the officially approved list.

**Comment by ssc327** [comment]
Thank you @Stratoco. Do you know if this is trying to make it into the approved list? If not, any reason why not?
