### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by DavBebawy** [jfarmer08/ha-sengledapi#6]
Hi! This is my first HACS integration so I'm not sure if I'm following your directions correctly. I installed it through HACS and have added these lines of code in /config/configuration.yaml per your instructions, and have restarted HA a couple of time since but have seen no entities. Am I missing something?

<img width="531" alt="image" src="https://user-images.githubusercontent.com/52139648/89811449-b15d6580-db0c-11ea-893c-bf977f969be1.png">
<img width="919" alt="image" src="https://user-images.githubusercontent.com/52139648/89811705-08fbd100-db0d-11ea-8247-62bf5fff5a20.png">

**Comment by DavBebawy** [comment]
Update: I found two E11-G13 lights entities in my account, those are the A19 model. I have 3 BR30 light bulbs and the Sengled LED strip that are connected to my account but not showing here. And since I'm a newbie, is there a way to turn those entities into devices? 
<img width="733" alt="image" src="https://user-images.githubusercontent.com/52139648/89812716-8d9b1f00-db0e-11ea-9f6c-6d842984e337.png">

**Comment by jfarmer08** [comment]
If you want to enable debug logs I can try to add support for the BR30 bulbs. Are they multi color?

**Comment by jfarmer08** [comment]
I am currently work on adding support for areas and devices. It will come at a later date.

**Comment by jfarmer08** [comment]
Do you have any logs so that i could add this>

**Comment by jfarmer08** [comment]
@DavBebawy 

Do you have any logs? There has been a few updates since this release, can you update and let me know how it goes?
