### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by gcohen79** [jfarmer08/ha-sengledapi#66]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System configuration**
System: 
HA Version: 
SengledApi Version:  

**configuration.yaml**

```yaml
<YOUR CONFIG HERE>
```

**home-assistant.log**
<!--
Ensure that your logger is set up by adding this to your configuration.yaml
logger:
  default: warning
  logs:
    custom_components.wyzeapi: debug

For additional information see the readme: https://github.com/jfarmer08/ha-sengledapi#reporting-an-issue
```
<PUT YOUR LOG HERE>
```

**Comment by Nameless11111** [comment]
Where is the bug report?
