### ISSUE TITLE
How do I add my sengled bulbs?

### ISSUE THREAD

**Issue by kspanks04** [jfarmer08/ha-sengledapi#67]
I installed using HAC and edited the config file as described, restarted but I'm not sure where to add the bulbs or where they should show up?

**Comment by rpowel** [comment]
Mine showed up under the entities menu automatically once they were added in the Sengled mobile app I had this integration configured. I would check the logs if they are still not showing up.

**Comment by kspanks04** [comment]
Thanks, does this require the mobile home assistant app to be working because I've never gotten it to work...

**Comment by jfarmer08** [comment]
This does not require HA App.  Not all bulbs are supported, but must be working on the Sengled App.
