### ISSUE TITLE
[Bug] No longer works for me

### ISSUE THREAD

**Issue by Grey-Lancaster** [jfarmer08/ha-sengledapi#76]
**Describe the bug**Detected blocking call to putrequest inside the event loop. This is causing stability issues. Please report issue to the custom component author for sengledapi doing blocking calls at custom_components/sengledapi/sengledapi/devices/request.py, line 64: r = requests.post(self._url, headers=self._header, data=self._payload)
2:53:02 PM – (WARNING) util/async_.py - message first occurred at 2:53:02 PM and shows up 2 times
Error during setup of component sengledapi
2:53:02 PM – (ERROR) util/async_.py

**Comment by jfarmer08** [comment]
Check your username and password.
