### ISSUE TITLE
Error with the integration after HA reboot

### ISSUE THREAD

**Issue by maxperron11** [jfarmer08/ha-sengledapi#92]
**Describe the bug**

After HA reboot I noticed the integration error and I lost all my wifi bulb entities.

So, I logged out of the Sengled application to notice that I'm not able to log back in anymore.

Does anyone have the same? Suspecting issue with Sengled but I cannot find anything on their website... 

Thanks

**Comment by Valdorama** [comment]
Yeah exact same behaviour here. Sengled mobile app says "you don't have an internet connection".

**Comment by maxperron11** [comment]
Thanks for the confirmation! I have the same here.

**Comment by sqorpo** [comment]
same issue

**Comment by mpipeling** [comment]
Same loss of function of integration. 
Logs reference request.py: 
"_Detected blocking call to putrequest inside the event loop by custom integration 'sengledapi' at custom_components/sengledapi/sengledapi/devices/request.py, line 40: r = requests.post(self._url, headers=self._header, data=self._payload), please report it to the author of the 'sengledapi' custom integration_"

**Comment by mpipeling** [comment]
> Same loss of function of integration. Logs reference request.py: "_Detected blocking call to putrequest inside the event loop by custom integration 'sengledapi' at custom_components/sengledapi/sengledapi/devices/request.py, line 40: r = requests.post(self._url, headers=self._header, data=self._payload), please report it to the author of the 'sengledapi' custom integration_"

So... either fortuitous timing or this [very odd] fix worked for me:
- made backup of request.py file
- completely gummed up request.py file with an erroneous async function call [specifically- changed line 40 to use "await hass.async_add_executor_job" in place of "requests.post"]
- as noted, this resulted in notification of failed load & multiple errors upon HA restart
- replaced 'gummed up' request.py file with original request.py file that I had backed up
- restarted HA
- all lights back online & functional via HA

?? can't explain it but it's working now so ??

**Comment by Valdorama** [comment]
Up and running now too. First checked Sengled app on phone and it's back to normal, so rebooted HA and the integration is also working again. So it was most likely some outage at Sengled's end.

**Comment by maxperron11** [comment]
Sengled Outage, fixed by provider.
